"""init_db

Revision ID: ebe88689216d
Revises: 
Create Date: 2023-03-04 18:04:19.444186

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebe88689216d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mc_query_mcservergroup",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("sv_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_table(
        "mc_query_mcserverprivate",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("sv_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mc_query_mcserverprivate")
    op.drop_table("mc_query_mcservergroup")
    # ### end Alembic commands ###
