[tool.poetry]
name = "migangbot"
version = "0.1.0"
description = "基于Nonebot2与go-cqhttp的机器人"
authors = ["LambdaYH"]
license = "MIT"
readme = "README.md"

[[tool.poetry.source]]
name = "tsinghua"
default = true
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = {extras = ["fastapi"], version = "^2.0.0rc3"}
nonebot-adapter-onebot = "^2.2.1"
nonebot-plugin-apscheduler = "^0.2.0"
ujson = "^5.7.0"
ruamel-yaml = "^0.17.21"
nonebot-plugin-imageutils = "^0.1.16"
nonebot-plugin-htmlrender = "^0.2.0.1"
async-lru = "^1.0.3"
tortoise-orm = {extras = ["accel", "asyncmy", "asyncpg"], version = "^0.19.3"}
nonebot-plugin-petpet = "^0.3.20"
nonebot-plugin-memes = "^0.3.10"
aiohttp = {extras = ["speedups"], version = "^3.8.4"}
lxml = "^4.9.2"
nonebot-plugin-word-bank2 = "^0.1.6"
tenacity = "^8.2.1"
fake-useragent = "^1.1.1"
aiocache = "^0.12.0"
azure-cognitiveservices-speech = "^1.25.0"
deep-translator = "^1.10.0"
pyzbar = "^0.1.9"
anyio = "^3.6.2"
mcstatus = "^10.0.1"
croniter = "^1.3.8"

[tool.poetry.group.dev.dependencies]
black = {version = "^23.1.0", allow-prereleases = true}

[tool.nonebot]
plugins = [
    "nonebot_plugin_petpet", 
    "nonebot_plugin_memes",
    "nonebot_plugin_word_bank2",
]
plugin_dirs = ["migang/plugins"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
