[tool.poetry]
name = "migangbot"
version = "0.1.0"
description = "基于Nonebot2与go-cqhttp的机器人"
authors = ["LambdaYH"]
license = "MIT"
readme = "README.md"

[[tool.poetry.source]]
name = "tsinghua"
default = true
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.poetry.dependencies]
python = "^3.10"
nonebot2 = {extras = ["fastapi"], version = "^2.0.0rc3"}
nonebot-adapter-onebot = "^2.2.1"
nonebot-plugin-apscheduler = "^0.2.0"
ujson = "^5.7.0"
ruamel-yaml = "^0.17.21"
nonebot-plugin-imageutils = "^0.1.16"
nonebot-plugin-htmlrender = "^0.2.0.1"
async-lru = "^1.0.3"
tortoise-orm = {extras = ["accel", "asyncmy", "asyncpg"], version = "^0.19.3"}
nonebot-plugin-petpet = "^0.3.20"
nonebot-plugin-memes = "^0.3.10"
aiohttp = {extras = ["speedups"], version = "^3.8.4"}
lxml = "^4.9.2"
nonebot-plugin-word-bank2 = "^0.1.6"
tenacity = "^8.2.1"
fake-useragent = "^1.1.1"
aiocache = "^0.12.0"
azure-cognitiveservices-speech = "^1.25.0"
deep-translator = "^1.10.0"
pyzbar = "^0.1.9"
anyio = "^3.6.2"
mcstatus = "^10.0.1"
croniter = "^1.3.8"
python-levenshtein = "^0.20.9"
nonebot-bison = "^0.7.0"
thefuzz = "^0.19.0"
nonebot-plugin-shindan = "^0.3.0"
nonebot-plugin-remake = "^0.2.7"
nonebot-plugin-emojimix = "^0.2.0"
nonebot-plugin-wordcloud = "^0.4.4"
nonebot-plugin-ddcheck = "^0.2.0"
nonebot-plugin-handle = "^0.2.0"
nonebot-plugin-imagetools = "^0.1.7"
nonebot-plugin-cocdicer = "^0.4.0"
nonebot-plugin-withdraw = "^0.2.3"
nonebot-plugin-hikarisearch = "^0.1.7"
nonebot-plugin-abstract = "^1.0.6"
nonebot-plugin-datastore = {extras = ["cli"], version = "^0.5.8"}
psutil = "^5.9.4"

[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.poetry.group.dev.dependencies]
black = {version = "^23.1.0", allow-prereleases = true}
isort = "^5.12.0"

[tool.nonebot]
plugins = [
    "nonebot_plugin_petpet", 
    "nonebot_plugin_memes",
    "nonebot_plugin_word_bank2",
    # "nonebot_bison",
    "nonebot_plugin_shindan",
    "nonebot_plugin_remake",
    "nonebot_plugin_emojimix",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_ddcheck",
    "nonebot_plugin_handle",
    "nonebot_plugin_imagetools",
    "nonebot_plugin_cocdicer",
    "nonebot_plugin_withdraw",
    "nonebot_plugin_hikarisearch",
    "nonebot_plugin_abstract"

]
plugin_dirs = ["migang/plugins", "migang/extension_plugins"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
