"""init_db

Revision ID: 5ea2851baf96
Revises: 
Create Date: 2023-03-04 17:58:54.105170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ea2851baf96"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aircon_aircon",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("env_temp", sa.Integer(), nullable=False),
        sa.Column("now_temp", sa.Float(), nullable=False),
        sa.Column("set_temp", sa.Integer(), nullable=False),
        sa.Column("last_update", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("wind_rate", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("ac_type", sa.Integer(), nullable=False),
        sa.Column("is_on", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("aircon_aircon")
    # ### end Alembic commands ###
