"""init_db

Revision ID: a99376a5b8e8
Revises: 
Create Date: 2023-02-25 11:06:16.118735

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a99376a5b8e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircon_aircon',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('env_temp', sa.Integer(), nullable=False),
    sa.Column('now_temp', sa.Float(), nullable=False),
    sa.Column('set_temp', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('wind_rate', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('ac_type', sa.Integer(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircon_aircon')
    # ### end Alembic commands ###
