"""init_db

Revision ID: 991f19b9e56a
Revises:
Create Date: 2023-05-06 16:18:01.209785

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "991f19b9e56a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ffxiv_fflogs_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("character_name", sa.String(), nullable=False),
        sa.Column("server_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ffxiv_fflogs_user")
    # ### end Alembic commands ###
