"""migrate data

修订 ID: b67acef6a240
父修订: c3c52d7c9d07
创建时间: 2023-10-29 18:37:34.419094

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from nonebot import logger
from sqlalchemy import inspect
from sqlalchemy.orm import Session
from sqlalchemy.ext.automap import automap_base

revision: str = "b67acef6a240"
down_revision: str | Sequence[str] | None = "c3c52d7c9d07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    if "ffxiv_fflogs_user_old" not in insp.get_table_names():
        return

    Base = automap_base()
    Base.prepare(autoload_with=op.get_bind())
    session = Session(op.get_bind())

    User = Base.classes.ffxiv_fflogs_user

    # 写入数据
    logger.info("ffxiv_fflogs: 发现来自 datastore 的数据，正在迁移...")
    for ds_user in (
        op.get_bind()
        .exec_driver_sql(
            "SELECT id, user_id, character_name, server_name FROM ffxiv_fflogs_user_old;"
        )
        .all()
    ):
        user = User(
            id=ds_user[0],
            user_id=ds_user[1],
            character_name=ds_user[2],
            server_name=ds_user[3],
        )
        session.add(user)

    session.commit()
    logger.info("ffxiv_fflogs: 迁移完成")
    op.drop_table("ffxiv_fflogs_user_old")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
