"""init_db

Revision ID: 59c6c1208f98
Revises: 
Create Date: 2023-02-19 21:15:28.640999

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "59c6c1208f98"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eorzean_zhanbu_eorzeanzhanburecorder",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("luck", sa.Integer(), nullable=False),
        sa.Column("yi", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ji", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dye", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("append_msg", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("basemap", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eorzean_zhanbu_eorzeanzhanburecorder")
    # ### end Alembic commands ###
