"""init_db

Revision ID: 663d3a69117f
Revises:
Create Date: 2023-03-04 18:01:50.113253

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "663d3a69117f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eorzean_zhanbu_eorzeanzhanburecorder",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("luck", sa.Integer(), nullable=False),
        sa.Column("yi", sa.String(64), nullable=False),
        sa.Column("ji", sa.String(64), nullable=False),
        sa.Column("dye", sa.String(64), nullable=False),
        sa.Column("append_msg", sa.String(255), nullable=False),
        sa.Column("basemap", sa.String(255), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eorzean_zhanbu_eorzeanzhanburecorder")
    # ### end Alembic commands ###
