"""init_db

Revision ID: e18c3ef83e29
Revises:
Create Date: 2023-03-22 22:32:18.869496

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e18c3ef83e29"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "russian_russianuser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("win_count", sa.Integer(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("make_money", sa.Integer(), nullable=False),
        sa.Column("lose_money", sa.Integer(), nullable=False),
        sa.Column("winning_streak", sa.Integer(), nullable=False),
        sa.Column("losing_streak", sa.Integer(), nullable=False),
        sa.Column("max_winning_streak", sa.Integer(), nullable=False),
        sa.Column("max_losing_streak", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("russian_russianuser")
    # ### end Alembic commands ###
